apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka01
  namespace: tools
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "mykafka"
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/k8s/pv/kafka01
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka02
  namespace: tools
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "mykafka"
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/k8s/pv/kafka02
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-kafka03
  namespace: tools
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "mykafka"
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/k8s/pv/kafka03
  persistentVolumeReclaimPolicy: Recycle
---
