localAPIEndpoint:        
  advertiseAddress: k8s.docker.internal  
kubernetesVersion: v1.19.2
networking:      
  podSubnet: "10.244.0.0/16"      
  serviceSubnet: 10.96.0.0/12    
---    
apiVersion: kubeproxy.config.k8s.io/v1alpha1    
kind: KubeProxyConfiguration    
featureGates:      
  SupportIPVSProxyMode: true    
mode: ipvs