apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.2
imageRepository: k8s.gcr.io
advertiseAddress: k8s.docker.internal
pod-network-cidr: 10.244.0.0/16 
networking:      
  podSubnet: "10.244.0.0/16"      
  serviceSubnet: 10.96.0.0/12   
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1    
kind: KubeProxyConfiguration    
featureGates:      
  SupportIPVSProxyMode: true    
mode: ipvs