# NodePort

apiVersion: v1
kind: Service
metadata:  
  name: myapp  
  namespace: default
spec:  
  type: NodePort  
  selector:    
    app: myapp    
    release: stabel  
  ports:  
    - name: http    
      port: 80    
      targetPort: 80
      nodePort: 30001