apiVersion: v1
kind: Service
metadata:  
  name: myapp  
  namespace: default
spec:  
  type: ClusterIP  
  selector:    
    app: myapp    
    release: stabel  
  ports:  
    - name: http    
      port: 80
      targetPort: 80