## 获取登陆初始密码
# kubectl exec -it `kubectl get pod | grep jenkins-server | awk '{print $1}'` -- cat /var/jenkins_home/secrets/initialAdminPassword
apiVersion: v1
kind: Service
metadata:
  name: jenkins-server
  namespace: tools
  labels:
    app: jenkins-server
spec:
  ports:
    - name: jenkins-port
      protocol: TCP
      port: 8080
      nodePort: 31081
  selector:
    app: jenkins-server
  type: NodePort