## Pod 中使用 ConfigMap -- 1. 使用 ConfigMap 来替代环境变量
# kubectl apply -f configmap-pod-env.yaml
# kubectl logs configmap-pod-env
# kubectl delete -f configmap-pod-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:  
  name: special-config  
  namespace: default
data:  
  special.how: very  
  special.type: charm

---

apiVersion: v1
kind: ConfigMap
metadata:  
  name: env-config  
  namespace: default
data:  
  log_level: INFO

---

apiVersion: v1
kind: Pod
metadata:  
  name: configmap-pod-env
spec:  
  containers:    
    - name: test-container      
      image: busybox      
      command: ["/bin/sh","-c","env"]      
      env:        
        - name: SPECIAL_LEVEL_KEY          
          valueFrom:            
            configMapKeyRef:              
              name: special-config              
              key: special.how
        - name: SPECIAL_TYPE_KEY          
          valueFrom:            
            configMapKeyRef:              
              name: special-config              
              key: special.type      
      envFrom:        
        - configMapRef:            
            name: env-config  
  restartPolicy: Never 