## 使用 Kuberctl 创建 docker registry 认证的 secret
# kubectl create secret docker-registry myregistrykey --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
# 在创建 Pod 的时候，通过imagePullSecrets来引用刚创建的 `myregistrykey`
apiVersion: v1
kind: Pod
metadata:  
  name: foo
spec:  
  containers:    
    - name: foo      
      image: nginx  
  imagePullSecrets:    
    - name: myregistry