
# Opaque 类型的数据是一个 map 类型，要求 value 是 base64 编码格式
apiVersion: v1
kind: Secret
metadata:  
  name: mysecret
  type: Opaque
data: 
  username: YWRtaW4=          # echo -n "admin" | base64 
  password: MWYyZDFlMmU2N2Rm  # echo -n "1f2d1e2e67df" | base64

---

# 将 Secret 挂载到 Volume 中
apiVersion: v1
kind: Pod
metadata: 
  name: seret-test  
  labels:        
    name: seret-test
spec:  
  volumes:  
  - name: secrets    
    secret:      
      secretName: mysecret  
  containers:  
  - image: busybox   
    name: db    
    volumeMounts:    
    - name: secrets      
      mountPath: ''      
      readOnly: true

---

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: pod-deploymnet
spec:  
  replicas: 1 
  selector:    
    matchLabels: 
      run: pod-deploymnet 
  template:
    metadata:      
      labels:        
        run: pod-deploymnet    
    spec:      
      containers:      
      - name: pod-1        
        image: nginx       
        ports:        
        - containerPort: 80 
        env:        
          - name: TEST_USER          
            valueFrom:            
              secretKeyRef:              
                name: mysecret              
                key: username        
          - name: TEST_PASSWORD          
            valueFrom:            
              secretKeyRef:              
                name: mysecret              
                key: password 

