# 存活检测
# kubectl apply -f livenessProbe-exec.yaml
# kubectl get pod liveness-exec-pod -w
# kubectl logs -f liveness-exec-pod
# kubectl delete -f livenessProbe-exec.yaml
apiVersion: v1
kind: Pod
metadata:  
  name: liveness-exec-pod  
  namespace: default
spec:  
  containers:  
    - name: liveness-exec-container    
      image: busybox    
      imagePullPolicy: IfNotPresent    
      command: ["/bin/sh","-c","touch /tmp/live ; sleep 60; rm -rf /tmp/live; sleep 3600;"]    
      livenessProbe:      
        exec:        
          command: ["test","-e","/tmp/live"]      
        initialDelaySeconds: 1      
        periodSeconds: 3