apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: tools
  labels:
    app: flink
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.11.2-scala_2.11
        command: # 解决官方版本不能够从Web UI 查看 Logs 以及Stdout
        - bash
        - -c
        - "sed -i 's/start-foreground/start/g' /docker-entrypoint.sh && \
        /docker-entrypoint.sh jobmanager && \
        tail -f /docker-entrypoint.sh"
        # args:
        # - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: tools
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.11.2-scala_2.11
        command: # 解决官方版本不能够从Web UI 查看 Logs 以及Stdout
        - bash
        - -c
        - "sed -i 's/start-foreground/start/g' /docker-entrypoint.sh && \
        /docker-entrypoint.sh taskmanager && \
        tail -f /docker-entrypoint.sh"
        # args:
        # - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager

---

apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: tools
spec:
  type: NodePort
  ports:
  - name: rpc
    port: 6123 
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
    nodePort: 30001
  selector:
    app: flink
    component: jobmanager