## DaemonSet
# 确保全部（或者一些）Node 上运行一个 Pod 的副本
# 当有 Node 加入集群时，也会为他们新增一个 Pod 
# 当有 Node 从集群移除时，这些 Pod 也会被回收
# 删除 DaemonSet 将会删除它创建的所有 Pod

## 典型用法
# 1. 运行集群存储 daemon，例如在每个 Node 上运行glusterd、ceph
# 2. 在每个 Node 上运行日志收集 daemon，例如fluentd、logstash
# 3. 在每个 Node 上运行监控 daemon，例如 Prometheus Node Exporter、collectd、Datadog 代理、New Relic 代理，或 Ganglia gmon


## 常用命令
# kubectl apply -f daemonset.yaml
# kubectl get pod -o wide
# kubectl delete -f daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:  
  name: deamonset-example  
  labels:    
    app: daemonset
spec:  
  selector:    
    matchLabels:      
      name: deamonset-example  
  template:    
    metadata:      
      labels:        
        name: deamonset-example    
    spec:      
      containers:      
        - name: daemonset-example        
          image: nginx