## Job 
# 负责批处理任务，即仅执行一次的任务，它保证批处理任务的一个或多个 Pod 成功结束
# # 特殊说明
# 1. spec.template格式同Pod
# 2. RestartPolicy仅支持Never或OnFailure
# 3. 单个Pod时，默认Pod成功运行后Job即结束
# 4. .spec.completions标志Job结束需要成功运行的Pod个数，默认为1
# 5. .spec.parallelism标志并行运行的Pod的个数，默认为1
# 6. spec.activeDeadlineSeconds标志失败Pod的重试最大时间，超过这个时间不会继续重试

## 常用命令
# kubectl apply -f job.yaml
# kubectl get pod
# kubectl describe pod job-example-xxxxx
# kubectl get job
# kubectl delete -f job.yaml

apiVersion: batch/v1
kind: Job
metadata:  
  name: job-example
spec:  
  template:    
    metadata:      
      name: job-example    
    spec:      
      containers:      
      - name: job-example        
        image: busybox        
        command: [ "sh","-c","echo `date '+%Y-%m-%d %H:%M:%S'`" ]      
      restartPolicy: Never